/* AUTH */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/* MEMO */
export const MEMO_POST = "MEMO_POST";
export const MEMO_POST_SUCCESS = "MEMO_POST_SUCCESS";
export const MEMO_POST_FAILURE = "MEMO_POST_FAILURE";

export const MEMO_LIST = "MEMO_LIST";
export const MEMO_LIST_SUCCESS = "MEMO_LIST_SUCCESS";
export const MEMO_LIST_FAILURE = "MEMO_LIST_FAILURE";

export const MEMO_EDIT = "MEMO_EDIT";
export const MEMO_EDIT_SUCCESS = "MEMO_EDIT_SUCCESS";
export const MEMO_EDIT_FAILURE = "MEMO_EDIT_FAILURE";

export const MEMO_REMOVE = "MEMO_REMOVE";
export const MEMO_REMOVE_SUCCESS = "MEMO_REMOVE_SUCCESS";
export const MEMO_REMOVE_FAILURE = "MEMO_REMOVE_FAILURE";

export const MEMO_STAR = "MEMO_STAR";
export const MEMO_STAR_SUCCESS = "MEMO_STAR_SUCCESS";
export const MEMO_STAR_FAILURE = "MEMO_STAR_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const GET_STREAMS = "GET_STREAMS";
export const GET_STREAMS_SUCCESS = "GET_STREAMS_SUCCESS";
export const GET_STREAMS_FAILURE = "GET_STREAMS_FAILURE";

export const MOONLIGHT_GET_HOSTS = "MOONLIGHT_GET_HOSTS";
export const MOONLIGHT_GET_HOSTS_SUCCESS = "MOONLIGHT_GET_HOSTS_SUCCESS";
export const MOONLIGHT_GET_HOSTS_FAILURE = "MOONLIGHT_GET_HOSTS_FAILURE";

export const MOONLIGHT_GET_APPS = "MOONLIGHT_GET_APPS";
export const MOONLIGHT_GET_APPS_SUCCESS = "MOONLIGHT_GET_APPS_SUCCESS";
export const MOONLIGHT_GET_APPS_FAILURE = "MOONLIGHT_GET_APPS_FAILURE";

export const MOONLIGHT_START_GAME = "MOONLIGHT_START_GAME";
export const MOONLIGHT_START_GAME_SUCCESS = "MOONLIGHT_START_GAME_SUCCESS";
export const MOONLIGHT_START_GAME_FAILURE = "MOONLIGHT_START_GAME_FAILURE";

export const MOONLIGHT_ADD_HOST = "MOONLIGHT_ADD_HOST";
export const MOONLIGHT_ADD_HOST_SUCCESS = "MOONLIGHT_ADD_HOST_SUCCESS";
export const MOONLIGHT_ADD_HOST_FAILURE = "MOONLIGHT_ADD_HOST_FAILURE";

export const NETWORKTEST_GET_SPEED = "SPEEDTEST_GET_SPEED";
export const NETWORKTEST_GET_SPEED_SUCCESS = "NETWORKTEST_GET_SPEED_SUCCESS";
export const NETWORKTEST_GET_SPEED_FAILURE = "NETWORKTEST_GET_SPEED_FAILURE";

